spring.application.name=careersync-backend


spring.datasource.url=jdbc:mysql://localhost:3306/careersync
spring.datasource.username=root
spring.datasource.password=yourDatabasepassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
